namespace FoP_IMT.Shared.Data.Enums.Tasks.Messages
{
    /// <summary>
    /// Role (source) of chat message
    /// </summary>
    public enum MessageRole
    {
        /// <summary>
        /// System message
        /// </summary>
        SYSTEM,

        /// <summary>
        /// Mesasge sent by user
        /// </summary>
        USER,

        /// <summary>
        /// Message generated by LLM
        /// </summary>
        AI
    }
}
